export enum AerKind { Null=0, Bool=1, Int=2, Float=3, Decimal=4, String=5, Bytes=6, DateTime=7, Duration=8, Array=9, Object=10, Table=11, Reference=12 }
export type AdvancedValue={kind:AerKind,data:any};
export type AerTable={columns:string[],rows:AdvancedValue[][]};
export type AerField={name:string,kind:AerKind,required?:boolean,unit?:string,min?:number,max?:number,meaning?:string};
export type AerSchema={name:string,fields:Record<string,AerField>};
export type PatchOperation={op:'add'|'replace'|'remove',path:string,value?:AdvancedValue};
export const v=(kind:AerKind,data:any):AdvancedValue=>({kind,data});
export const object=(data:Record<string,AdvancedValue>):AdvancedValue=>v(AerKind.Object,data);
export const array=(data:AdvancedValue[]):AdvancedValue=>v(AerKind.Array,data);
export const table=(columns:string[],rows:AdvancedValue[][]):AdvancedValue=>{if(!columns.length||new Set(columns).size!==columns.length||rows.some(r=>r.length!==columns.length))throw new Error('invalid AER table');return v(AerKind.Table,{columns:[...columns],rows:rows.map(r=>[...r])});};
const esc=(s:string)=>s.replace(/\\/g,'\\\\').replace(/"/g,'\\"').replace(/\n/g,'\\n');
export function scalar(x:AdvancedValue):string{switch(x.kind){case AerKind.Null:return '-';case AerKind.Bool:return x.data?'true':'false';case AerKind.Int:return BigInt(x.data).toString();case AerKind.Float:return String(x.data);case AerKind.Decimal:return String(x.data);case AerKind.String:return x.data&&!["-","true","false"].includes(x.data)&&!x.data.startsWith('@')&&!x.data.startsWith('dt"')&&!x.data.startsWith('dur"')&&!x.data.startsWith('b64"')&&!/[,:\n]/.test(x.data)?x.data:'"'+esc(x.data)+'"';case AerKind.Bytes:return 'b64"'+Buffer.from(x.data).toString('base64')+'"';case AerKind.DateTime:return 'dt"'+new Date(x.data).toISOString()+'"';case AerKind.Duration:return 'dur"'+String(x.data)+'"';case AerKind.Reference:return '@'+x.data;default:throw new Error('non-scalar');}}
export function dumps(value:AdvancedValue,header=true):string{const out=header?['@aer 1']:[];const emit=(k:string,x:AdvancedValue,n:number)=>{const p=' '.repeat(n);if(x.kind===AerKind.Object){out.push(p+k+':');for(const [a,b] of Object.entries(x.data))emit(a,b,n+2)}else if(x.kind===AerKind.Table){out.push(`${p}${k}[${x.data.rows.length}]{${x.data.columns.join(',')}}:`);for(const r of x.data.rows)out.push(' '.repeat(n+2)+r.map(scalar).join(','))}else if(x.kind===AerKind.Array&&x.data.every((y:AdvancedValue)=>![AerKind.Object,AerKind.Array,AerKind.Table].includes(y.kind))){out.push(`${p}${k}[${x.data.length}]:`+x.data.map(scalar).join(','))}else if(x.kind===AerKind.Array){out.push(p+k+':');x.data.forEach((y:AdvancedValue,i:number)=>emit(String(i),y,n+2))}else out.push(p+k+':'+scalar(x));};if(value.kind===AerKind.Object)for(const [k,x] of Object.entries(value.data))emit(k,x,0);else emit('value',value,0);return out.join('\n')+'\n';}
const cat=(a:number[],b:Uint8Array)=>{for(const x of b)a.push(x)};
const i64=(n:bigint)=>{const b=new Uint8Array(8);new DataView(b.buffer).setBigInt64(0,n,true);return b};
const str=(a:number[],s:string)=>{const b=new TextEncoder().encode(s);cat(a,i64(BigInt(b.length)));cat(a,b)};
const DATE_TICKS=621355968000000000n;
export function encodeBinary(value:AdvancedValue):Uint8Array{const out=[65,69,82,66,1];const enc=(x:AdvancedValue)=>{out.push(x.kind);switch(x.kind){case AerKind.Null:break;case AerKind.Bool:out.push(x.data?1:0);break;case AerKind.Int:cat(out,i64(BigInt(x.data)));break;case AerKind.Float:{const b=new Uint8Array(8);new DataView(b.buffer).setFloat64(0,x.data,true);cat(out,b);break}case AerKind.Decimal:case AerKind.String:case AerKind.Reference:str(out,String(x.data));break;case AerKind.Bytes:cat(out,i64(BigInt(x.data.length)));cat(out,x.data);break;case AerKind.DateTime:{const ms=x.data instanceof Date?x.data.getTime():new Date(x.data).getTime();cat(out,i64(DATE_TICKS+BigInt(ms)*10000n));break}case AerKind.Duration:cat(out,i64(BigInt(x.data)));break;case AerKind.Array:cat(out,i64(BigInt(x.data.length)));x.data.forEach(enc);break;case AerKind.Object:{const e=Object.entries(x.data);cat(out,i64(BigInt(e.length)));for(const [k,y] of e){str(out,k);enc(y)}break}case AerKind.Table:cat(out,i64(BigInt(x.data.columns.length)));x.data.columns.forEach((c:string)=>str(out,c));cat(out,i64(BigInt(x.data.rows.length)));x.data.rows.forEach((r:AdvancedValue[])=>r.forEach(enc));break}};enc(value);return new Uint8Array(out)}
export function decodeBinary(data:Uint8Array):AdvancedValue{if(data.length<5||new TextDecoder().decode(data.slice(0,4))!=='AERB'||data[4]!==1)throw new Error('invalid AERB header');let o=5;const need=(n:number)=>{if(o+n>data.length)throw new Error('truncated AERB payload');const x=data.slice(o,o+n);o+=n;return x};const n64=()=>new DataView(need(8).buffer).getBigInt64(0,true);const text=()=>new TextDecoder().decode(need(Number(n64())));const dec=():AdvancedValue=>{const k=need(1)[0];switch(k){case 0:return v(k,null);case 1:return v(k,need(1)[0]!==0);case 2:return v(k,n64());case 3:return v(k,new DataView(need(8).buffer).getFloat64(0,true));case 4:case 5:case 12:return v(k,text());case 6:return v(k,need(Number(n64())));case 7:return v(k,new Date(Number((n64()-DATE_TICKS)/10000n)));case 8:return v(k,n64());case 9:{const n=Number(n64()),a:AdvancedValue[]=[];for(let i=0;i<n;i++)a.push(dec());return v(k,a)}case 10:{const n=Number(n64()),m:Record<string,AdvancedValue>={};for(let i=0;i<n;i++)m[text()]=dec();return v(k,m)}case 11:{const c=Number(n64()),cols:string[]=[];for(let i=0;i<c;i++)cols.push(text());const r=Number(n64()),rows:AdvancedValue[][]=[];for(let i=0;i<r;i++){const row:AdvancedValue[]=[];for(let j=0;j<c;j++)row.push(dec());rows.push(row)}return v(k,{columns:cols,rows})}default:throw new Error(`unsupported AER kind ${k}`)}};const result=dec();if(o!==data.length)throw new Error('trailing AERB payload');return result;}
const splitCsv=(s:string)=>{const out:string[]=[];let start=0,q=false,escp=false;for(let i=0;i<s.length;i++){const c=s[i];if(escp){escp=false;continue}if(c==='\\'&&q){escp=true;continue}if(c==='"')q=!q;else if(c===','&&!q){out.push(s.slice(start,i).trim());start=i+1;}}out.push(s.slice(start).trim());return out};
const parseScalar=(s:string):AdvancedValue=>{if(s==='-')return v(AerKind.Null,null);if(s==='true'||s==='false')return v(AerKind.Bool,s==='true');if(s.startsWith('@')&&s.length>1)return v(AerKind.Reference,s.slice(1));if(s.startsWith('b64"')&&s.endsWith('"'))return v(AerKind.Bytes,Uint8Array.from(Buffer.from(s.slice(4,-1),'base64')));if(s.startsWith('dt"')&&s.endsWith('"'))return v(AerKind.DateTime,new Date(s.slice(3,-1)));if(s.startsWith('dur"')&&s.endsWith('"'))return v(AerKind.Duration,BigInt(s.slice(5,-1)));if(s.length>=2&&s.startsWith('"')&&s.endsWith('"'))return v(AerKind.String,s.slice(1,-1).replace(/\\n/g,'\n').replace(/\\"/g,'"').replace(/\\\\/g,'\\'));if(/^[+-]?\d+$/.test(s))return v(AerKind.Int,BigInt(s));if(/[.eE]/.test(s)&&!Number.isNaN(Number(s)))return v(AerKind.Float,Number(s));return v(AerKind.String,s)};
export function loadsAdvanced(text:string):AdvancedValue{const lines=text.replace(/\r/g,'').split('\n').filter(x=>x.trim()&&!x.trimStart().startsWith('#'));while(lines[0]?.trimStart().startsWith('@'))lines.shift();if(!lines.length)throw new Error('empty AER document');const block=(start:number,indent:number):[Record<string,AdvancedValue>,number]=>{const out:Record<string,AdvancedValue>={};let pos=start;while(pos<lines.length){const raw=lines[pos],ind=raw.length-raw.trimStart().length;if(ind<indent)break;if(ind>indent)throw new Error('invalid indentation');const line=raw.trim(),at=line.indexOf(':');if(at<1)throw new Error('invalid AER line');const key=line.slice(0,at),rest=line.slice(at+1).trim();pos++;const tm=key.lastIndexOf(']{'),op=key.lastIndexOf('[');if(op>0&&tm>op&&key.endsWith('}')&&!rest){const n=Number(key.slice(op+1,tm)),name=key.slice(0,op),cols=key.slice(tm+2,-1).split(',').map(x=>x.trim()),rows:AdvancedValue[][]=[];for(let i=0;i<n;i++){if(pos>=lines.length)throw new Error('unexpected end of table');const vals=splitCsv(lines[pos++].trim());if(vals.length!==cols.length)throw new Error('table column count mismatch');rows.push(vals.map(parseScalar));}out[name]=table(cols,rows);continue}const am=key.lastIndexOf('[');if(am>0&&key.endsWith(']')&&rest){const n=Number(key.slice(am+1,-1)),vals=splitCsv(rest);if(vals.length!==n)throw new Error('array count mismatch');out[key.slice(0,am)]=array(vals.map(parseScalar));continue}if(!rest){if(pos<lines.length&&lines[pos].length-lines[pos].trimStart().length>ind){const r=block(pos,ind+2);out[key]=object(r[0]);pos=r[1]}else out[key]=object({})}else out[key]=parseScalar(rest)}return [out,pos]};return object(block(0,0)[0]);}
export function validate(schema:AerSchema,value:AdvancedValue):string[]{if(value.kind!==AerKind.Object)return [`${schema.name}: expected object`];const errors:string[]=[];for(const [name,f] of Object.entries(schema.fields)){const x=value.data[name];if(x===undefined){if(f.required)errors.push(`${name}: required`);continue}if(f.kind!==x.kind&&!(f.kind===AerKind.Decimal&&x.kind===AerKind.Int)){errors.push(`${name}: expected ${AerKind[f.kind]}`);continue}if(f.min!==undefined&&typeof x.data==='number'&&x.data<f.min)errors.push(`${name}: below minimum`);if(f.max!==undefined&&typeof x.data==='number'&&x.data>f.max)errors.push(`${name}: above maximum`);}return errors;}
export function applyPatch(root:AdvancedValue,ops:PatchOperation[]):AdvancedValue{let cur=root;for(const op of ops)cur=mutate(cur,op.path.split('/').filter(Boolean),0,op);return cur;}
function mutate(node:AdvancedValue,p:string[],i:number,op:PatchOperation):AdvancedValue{if(i===p.length-1)return leaf(node,p[i],op);if(node.kind===AerKind.Object){if(!(p[i] in node.data))throw new Error('patch path does not exist');return object({...node.data,[p[i]]:mutate(node.data[p[i]],p,i+1,op)})}if(node.kind===AerKind.Array){const a=[...node.data],n=Number(p[i]);if(!Number.isInteger(n)||n<0||n>=a.length)throw new Error('invalid array index');a[n]=mutate(a[n],p,i+1,op);return array(a)}throw new Error('patch target is not traversable');}
function leaf(node:AdvancedValue,key:string,op:PatchOperation):AdvancedValue{if(node.kind===AerKind.Object){const d={...node.data};if(op.op==='remove'){if(!(key in d))throw new Error('patch field does not exist');delete d[key]}else{if(op.value===undefined)throw new Error('patch value required');d[key]=op.value}return object(d)}if(node.kind===AerKind.Array){const a=[...node.data],n=Number(key);if(!Number.isInteger(n)||n<0||n>=a.length)throw new Error('invalid array index');if(op.op==='remove')a.splice(n,1);else{if(op.value===undefined)throw new Error('patch value required');a[n]=op.value}return array(a)}throw new Error('patch target is not mutable');}
export function encodeFrame(v:AdvancedValue):Uint8Array{const p=encodeBinary(v),o=new Uint8Array(9+p.length);o.set([65,69,82,70,1],0);new DataView(o.buffer).setUint32(5,p.length,true);o.set(p,9);return o;}
export function decodeFrames(data:Uint8Array,maxFrameBytes=16*1024*1024):AdvancedValue[]{const out:AdvancedValue[]=[];let o=0;while(o<data.length){if(data.length-o<9)throw new Error('AER008 truncated frame header');if(new TextDecoder().decode(data.slice(o,o+4))!=='AERF'||data[o+4]!==1)throw new Error('AER009 invalid frame');const n=new DataView(data.buffer,data.byteOffset+o+5,4).getUint32(0,true);if(n>maxFrameBytes)throw new Error('AER006 frame too large');if(data.length-o-9<n)throw new Error('AER008 truncated frame payload');out.push(decodeBinary(data.slice(o+9,o+9+n)));o+=9+n;}return out;}
