package aer

import("bytes";"encoding/binary";"encoding/base64";"fmt";"strconv";"strings")
type Kind byte
const(Null Kind=iota; Bool; Int; Float; Decimal; String; Bytes; DateTime; Duration; Array; Object; Table; Reference)
type Value struct{Kind Kind; Data any}
func From(v any)Value{switch x:=v.(type){case nil:return Value{Null,nil};case bool:return Value{Bool,x};case int:return Value{Int,int64(x)};case int64:return Value{Int,x};case float64:return Value{Float,x};case string:return Value{String,x};case []byte:return Value{Bytes,x};case []Value:return Value{Array,x};case map[string]Value:return Value{Object,x};default:panic(fmt.Sprintf("unsupported %T",v))}}
func Dumps(v Value)string{var b strings.Builder;b.WriteString("@aer 1\n"); var emit func(string,Value,int); emit=func(k string,x Value,n int){p:=strings.Repeat(" ",n);if x.Kind==Object{b.WriteString(p+k+":\n");for a,z:=range x.Data.(map[string]Value){emit(a,z,n+2)}}else if x.Kind==Array{a:=x.Data.([]Value);ok:=true;for _,z:=range a{if z.Kind==Object||z.Kind==Array{ok=false}};if ok{b.WriteString(fmt.Sprintf("%s%s[%d]:",p,k,len(a)));for i,z:=range a{if i>0{b.WriteByte(',')};b.WriteString(scalar(z))};b.WriteByte('\n')}else{b.WriteString(p+k+":\n");for i,z:=range a{emit(strconv.Itoa(i),z,n+2)}}}else{b.WriteString(p+k+":"+scalar(x)+"\n")}};if v.Kind==Object{for k,x:=range v.Data.(map[string]Value){emit(k,x,0)}}else{emit("value",v,0)};return b.String()}
func scalar(v Value)string{switch v.Kind{case Null:return "-";case Bool:if v.Data.(bool){return "true"};return "false";case Int:return strconv.FormatInt(v.Data.(int64),10);case Float:return strconv.FormatFloat(v.Data.(float64),'g',-1,64);case String:s:=v.Data.(string);if s!=""&&!strings.ContainsAny(s,",:\n")&&s!="-"&&s!="true"&&s!="false"&&!strings.HasPrefix(s,"@"){return s};return `"`+strings.NewReplacer(`\`,`\\`,`"`,`\"`,`\n`,`\\n`).Replace(s)+`"`;case Bytes:return `b64"`+base64.StdEncoding.EncodeToString(v.Data.([]byte))+`"`;case Reference:return "@"+v.Data.(string)};panic("non-scalar")}
func Encode(v Value)[]byte{b:=bytes.NewBuffer(append([]byte("AERB"),1));enc(b,v);return b.Bytes()}
func put(b *bytes.Buffer,v int64){_ = binary.Write(b,binary.LittleEndian,v)}
func str(b *bytes.Buffer,s string){put(b,int64(len([]byte(s))));b.WriteString(s)}
func enc(b *bytes.Buffer,v Value){b.WriteByte(byte(v.Kind));switch v.Kind{case Null:return;case Bool:if v.Data.(bool){b.WriteByte(1)}else{b.WriteByte(0)};case Int:put(b,v.Data.(int64));case Float:binary.Write(b,binary.LittleEndian,v.Data.(float64));case Decimal,String,Reference:str(b,fmt.Sprint(v.Data));case Bytes:put(b,int64(len(v.Data.([]byte))));b.Write(v.Data.([]byte));case Array:a:=v.Data.([]Value);put(b,int64(len(a)));for _,x:=range a{enc(b,x)};case Object:o:=v.Data.(map[string]Value);put(b,int64(len(o)));for k,x:=range o{str(b,k);enc(b,x)}}}
func Decode(d []byte)(Value,error){if len(d)<5||string(d[:4])!="AERB"||d[4]!=1{return Value{},fmt.Errorf("invalid AERB header")};v,_,e:=dec(d,5);return v,e}
func read(d []byte,o *int,n int)([]byte,error){if *o+n>len(d){return nil,fmt.Errorf("truncated AERB payload")};x:=d[*o:*o+n];*o+=n;return x,nil}
func i64(d []byte,o *int)(int64,error){x,e:=read(d,o,8);if e!=nil{return 0,e};return int64(binary.LittleEndian.Uint64(x)),nil}
func strd(d []byte,o *int)(string,error){n,e:=i64(d,o);if e!=nil||n<0||n>int64(len(d)-*o){return "",fmt.Errorf("invalid string length")};x,e:=read(d,o,int(n));return string(x),e}
func dec(d []byte,o int)(Value,int,error){x,e:=read(d,&o,1);if e!=nil{return Value{},o,e};k:=Kind(x[0]);switch k{case Null:return From(nil),o,nil;case Bool:x,e=read(d,&o,1);return From(x[0]!=0),o,e;case Int:n,e:=i64(d,&o);return From(n),o,e;case Float:x,e=read(d,&o,8);if e!=nil{return Value{},o,e};return From(float64From(x)),o,nil;case String,Decimal,Reference:s,e:=strd(d,&o);return Value{k,s},o,e;case Bytes:n,e:=i64(d,&o);if e!=nil{return Value{},o,e};x,e=read(d,&o,int(n));return Value{Bytes,x},o,e;case Array:n,e:=i64(d,&o);if e!=nil||n<0{return Value{},o,fmt.Errorf("invalid array length")};a:=make([]Value,n);for i:=range a{a[i],o,e=dec(d,o);if e!=nil{return Value{},o,e}};return Value{Array,a},o,nil;case Object:n,e:=i64(d,&o);if e!=nil||n<0{return Value{},o,fmt.Errorf("invalid object length")};m:=map[string]Value{};for i:=int64(0);i<n;i++{k,e:=strd(d,&o);if e!=nil{return Value{},o,e};z,no,e:=dec(d,o);o=no;if e!=nil{return Value{},o,e};m[k]=z};return Value{Object,m},o,nil};return Value{},o,fmt.Errorf("unsupported kind %d",k)}
func float64From(b []byte)float64{return *(*float64)(unsafe.Pointer(&b[0]))}
