package aer

import("encoding/base64";"fmt";"strconv";"strings";"time")

func LoadsFull(text string)(Value,error){lines:=[]string{};for _,l:=range strings.Split(strings.ReplaceAll(strings.ReplaceAll(text,"\r\n","\n"),"\r","\n"),"\n"){if strings.TrimSpace(l)!=""&&!strings.HasPrefix(strings.TrimSpace(l),"#"){lines=append(lines,l)}};for len(lines)>0&&strings.HasPrefix(strings.TrimSpace(lines[0]),"@"){lines=lines[1:]};if len(lines)==0{return Value{},fmt.Errorf("empty AER document")};m,_,e:=parseBlock(lines,0,0);if e!=nil{return Value{},e};return Value{Object,m},nil}
func indentOf(s string)int{return len(s)-len(strings.TrimLeft(s," "))}
func parseBlock(lines []string,pos,ind int)(map[string]Value,int,error){out:=map[string]Value{};for pos<len(lines){raw:=lines[pos];cur:=indentOf(raw);if cur<ind{return out,pos,nil};if cur>ind{return nil,pos,fmt.Errorf("invalid indentation")};line:=strings.TrimSpace(raw);at:=strings.IndexByte(line,':');if at<1{return nil,pos,fmt.Errorf("invalid AER line")};key,rest:=line[:at],strings.TrimSpace(line[at+1:]);pos++;if op:=strings.LastIndex(key,"[");op>0&&strings.Contains(key[op:],"]{")&&strings.HasSuffix(key,"}")&&rest==""{mid:=strings.Index(key[op:],"]{");mid+=op;n,_:=strconv.Atoi(key[op+1:mid]);name:=key[:op];cols:=strings.Split(key[mid+2:len(key)-1],",");rows:=make([][]Value,n);for i:=0;i<n;i++{if pos>=len(lines){return nil,pos,fmt.Errorf("unexpected end of table")};vals:=splitCSV(strings.TrimSpace(lines[pos]));pos++;if len(vals)!=len(cols){return nil,pos,fmt.Errorf("table column count mismatch")};rows[i]=make([]Value,len(vals));for j,x:=range vals{rows[i][j]=parseScalarFull(strings.TrimSpace(x))}};out[name]=MakeTable(cols,rows);continue};if op:=strings.LastIndex(key,"[");op>0&&strings.HasSuffix(key,"]")&&rest!=""{n,e:=strconv.Atoi(key[op+1:len(key)-1]);if e!=nil{return nil,pos,e};vals:=splitCSV(rest);if len(vals)!=n{return nil,pos,fmt.Errorf("array count mismatch")};a:=make([]Value,n);for i,x:=range vals{a[i]=parseScalarFull(strings.TrimSpace(x))};out[key[:op]]=Value{Array,a};continue};if rest==""{if pos<len(lines)&&indentOf(lines[pos])>cur{child,no,e:=parseBlock(lines,pos,cur+2);if e!=nil{return nil,pos,e};out[key]=Value{Object,child};pos=no}else{out[key]=Value{Object,map[string]Value{}}}}else{out[key]=parseScalarFull(rest)}};return out,pos,nil}
func splitCSV(s string)[]string{var out []string;start:=0;q:=false;esc:=false;for i,c:=range s{if esc{esc=false;continue};if c=='\\'&&q{esc=true;continue};if c=='"'{q=!q}else if c==','&&!q{out=append(out,strings.TrimSpace(s[start:i]));start=i+1}};return append(out,strings.TrimSpace(s[start:]))}
func parseScalarFull(s string)Value{if s=="-"{return Value{Null,nil}};if s=="true"{return Value{Bool,true}};if s=="false"{return Value{Bool,false}};if strings.HasPrefix(s,"@")&&len(s)>1{return Value{Reference,s[1:]}};if strings.HasPrefix(s,"b64\"")&&strings.HasSuffix(s,"\""){b,_:=base64.StdEncoding.DecodeString(s[4:len(s)-1]);return Value{Bytes,b}};if strings.HasPrefix(s,"dt\"")&&strings.HasSuffix(s,"\""){t,e:=time.Parse(time.RFC3339Nano,s[3:len(s)-1]);if e==nil{return Value{DateTime,t}}};if strings.HasPrefix(s,"dur\"")&&strings.HasSuffix(s,"\""){d,e:=time.ParseDuration(s[5:len(s)-1]);if e==nil{return Value{Duration,d}}};if len(s)>=2&&s[0]=='"'&&s[len(s)-1]=='"'{return Value{String,strings.ReplaceAll(strings.ReplaceAll(strings.ReplaceAll(s[1:len(s)-1],"\\n","\n"),"\\\"","\""),"\\\\","\\")}};if n,e:=strconv.ParseInt(s,10,64);e==nil{return Value{Int,n}};if f,e:=strconv.ParseFloat(s,64);e==nil{return Value{Float,f}};return Value{String,s}}
